### ISSUE TITLE
SharedPreference token

### ISSUE THREAD

**Issue by restia79** [lazycatlabs/flutter_auth_app#1]
Malam gan,
Sebelumnya terima kasih banyak project flutter nya.

Saya mau bertanya mengenai token saat menggunakan postRequest,
Ketika login dan mendapatkan token, setelah itu saya cek token nya ada isi.

Tetapi ketika saya mau loading data dari api menggunakan method POST dan memanggil token yang ada di PrefManager, 
isi nya null. 

Mohon bantuannya gan, saat memanggil token kembali yang ada di prefManager.

Terima kasih

**Comment by Lzyct** [comment]
Halo @restia79 ,
bisa dijelaskan issue nya lebih detail?

Misalnya sertakan snipped/screenshot code nya, atau cara reproduce issuenya.

Terima kasih

**Comment by restia79** [comment]
![Flutter token](https://user-images.githubusercontent.com/103842257/163753186-19fc84bb-10f5-4dd3-86b4-059bdd2dc442.png)
Saya menggunakan api yg saya buat sendiri.

![image](https://user-images.githubusercontent.com/103842257/163753288-422bc734-689a-4073-bfda-8620f3bf20b6.png)
Untuk codingan dio nya tidak saya ubah.

Kira-kira seperti ini ini..

**Comment by Lzyct** [comment]
Bisa di log dulu nggak token yang di sharedPref nya sebelum panggil postData nya?

**Comment by restia79** [comment]
Maaf gan, saya baru belajar flutternya..
Saya coba tampilin token ke title ada isi token nya..
menggunakan sl<PrefManager>().token.toString()
![WhatsApp Image 2022-04-18 at 15 05 24](https://user-images.githubusercontent.com/103842257/163777880-bc20676c-fc26-44e4-9af1-cca09b65917e.jpeg)
Terima kasih banyak gan,..

**Comment by Lzyct** [comment]
Coba langsung panggil aja `sl().token.toString()` 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/1531684/163822508-f4c760d9-e15c-48da-aaec-bdd3b32e553a.png">

di sini, soalnya saya gk tau kodenya kayak gimana, alur flow dari UI ke data nya

**Comment by restia79** [comment]
Terima kasih kan sudah direspon lagi.

Setelah saya debug, jadi alur nya dari project yg agan share..
1. Saat aplikasi dijalankan, aplikasi panggil await service locator.
![image](https://user-images.githubusercontent.com/103842257/163906098-e2cf5f24-5543-4e6b-bc37-f6fbe7cf3715.png)
![image](https://user-images.githubusercontent.com/103842257/163906368-77d7eddc-6fdd-4510-bec5-777bd45a78f0.png)
disini sudah menyimpan Request header nya (token masih dalam keaadan kosong).

2. Ketika aplikasi login lalu mendapatkan token. (Pada saat login token belum dibutuhkan, jadi tidak masalah)
3. Lalu pada saat ingin mengambil data menggunakan post dan butuh token.
![image](https://user-images.githubusercontent.com/103842257/163906777-a4621f2d-5512-49a8-9363-e1da8bf08fc3.png)
Ketima menjalankan post user "_client.postRequest( " tidak memanggil dioClient lagi,
> auth_remote_datasources.dart 
> @override
>   Future<UsersResponse> users(UsersParams userParams) async {
>     try {
>       final _response = await _client.postRequest(
>         ListApi.users,
>         data: userParams.toJson(),
>       );
>       final _result = UsersResponse.fromJson(_response.data);
> 
>       if (_response.statusCode == 200) {
>         return _result;
>       } else {
>         throw ServerException(_result.error);
>       }
>     } on ServerException catch (e) {
>       throw ServerException(e.message);
>     }
>   } 

Jadi yang mau saya tanyakan, bagaimana supaya ketika memanggil postRequest memanggil dioClient kembali.

Terima kasih banyak gan.

**Comment by Lzyct** [comment]
Oh iya kayaknya issue di Dependencies Injection, udah saya resolved, coba di cek aja commit references nya

Makasih, saya close yah. Klo masih ada issue lagi silakan di re-open issue nya.
