### ISSUE TITLE
Undefined name 'Strings'. What is it exactly?

### ISSUE THREAD

**Issue by felipecastrosales** [lazycatlabs/flutter_auth_app#11]
What does the Strings class actually accomplish and how do we access it?

I didn't find any point that enlightened me about this so that I could run the project without errors. 

For example: 

![image](https://user-images.githubusercontent.com/59374587/201498289-59b4c0e1-d8c6-433e-9141-daf47112add1.png)

In what I can collaborate, I make myself available for help. :)

**Comment by programmer-b** [comment]
export 'generated/strings.dart';

No folder called generated in core

**Comment by Lzyct** [comment]
Hi @felipecastrosales @programmer-b 
That's Strings class is generated by intl, I already updated the [documentation](https://github.com/lazycatlabs/flutter_auth_app/commit/3b5c4820770eeabb43fa21800e50a8218cfcc576) about how to resolve that issues
