### ISSUE TITLE
What's the usage of CoreMapper ?

### ISSUE THREAD

**Issue by bloopdex** [lazycatlabs/flutter_auth_app#28]
Can you explain the usage of core mapper in the core folder :
lib/core/core_mapper.dart

**Comment by Lzyct** [comment]
Hi @bloopdex, 
That's an unused file, I forgot to remove it 😅

Previously I used that mixin to map Response data to Entitiy, but right now I do that in the model_responses.

You can see the sample in the features/users/data/models/users_response.dart

I do the mapping from `API User response` to `Users Entity`

![image](https://github.com/user-attachments/assets/0b035995-786a-43e2-99fd-0253f2d93d2b)


I hope I answered your question

Thank you.
